<?php

namespace Database\Seeders\Training\Certification;

use App\Models\CertificationProgram;
use Database\Seeders\Training\CurriculumSeeder;

class AdministratorCertificationSeeder extends CurriculumSeeder
{
    public function run(): void
    {
        $program = CertificationProgram::query()->where('code', 'SCA')->where('version', '1.0')->firstOrFail();

        $questions = [
            ['question'=>'Seorang TU tidak dapat mengakses unitnya. Tindakan awal yang paling tepat adalah?','options'=>['A'=>'Jadikan Super Admin','B'=>'Periksa status user, assignment unit, status unit, dan role','C'=>'Reset seluruh permission','D'=>'Hapus lalu buat akun baru'],'correct'=>'B','explanation'=>'Diagnosis akses dimulai dari state user, unit, dan role sebelum memperluas privilege.'],
            ['question'=>'Prinsip least privilege berarti?','options'=>['A'=>'Semua staff mendapat akses penuh saat periode sibuk','B'=>'User menerima hak minimum yang dibutuhkan untuk tugasnya','C'=>'Hanya Super Admin boleh login','D'=>'Permission tidak perlu direview setelah dibuat'],'correct'=>'B','explanation'=>'Least privilege membatasi hak ke kebutuhan tugas aktual.'],
            ['type'=>'tf','question'=>'Admin Unit dan TU seharusnya bekerja dalam scope unit yang ditetapkan pada akunnya.','correct'=>true,'explanation'=>'Scope unit membatasi data dan operasi staff unit.'],
            ['type'=>'tf','question'=>'Akun bersama lebih baik daripada akun personal karena mempermudah pergantian shift.','correct'=>false,'explanation'=>'Akun bersama merusak akuntabilitas audit dan memperbesar risiko credential.'],
            ['question'=>'Ketika staff keluar dari organisasi, tindakan yang paling tepat terhadap akunnya adalah?','options'=>['A'=>'Hapus seluruh histori user','B'=>'Biarkan aktif untuk berjaga-jaga','C'=>'Nonaktifkan akses dan pertahankan histori audit','D'=>'Ubah password lalu bagikan ke pengganti'],'correct'=>'C','explanation'=>'Offboarding harus menghentikan akses tanpa menghilangkan jejak historis.'],
            ['question'=>'Perbedaan utama konfigurasi global dan unit adalah?','options'=>['A'=>'Konfigurasi global selalu disimpan di .env','B'=>'Global berdampak lintas unit, konfigurasi unit hanya pada scope unit terkait','C'=>'Konfigurasi unit tidak boleh diubah','D'=>'Keduanya selalu berdampak sama'],'correct'=>'B','explanation'=>'Scope dampak menentukan tempat dan kontrol perubahan.'],
            ['type'=>'tf','question'=>'Perubahan branding global tidak memerlukan verifikasi karena hanya bersifat visual.','correct'=>false,'explanation'=>'Branding tetap perlu dicek pada surface yang terdampak agar tidak merusak pengalaman pengguna.'],
            ['question'=>'Unit perlu dihentikan dari operasi tetapi histori harus dipertahankan. Pilihan terbaik adalah?','options'=>['A'=>'Hard delete unit','B'=>'Nonaktifkan unit melalui lifecycle/control yang tersedia','C'=>'Hapus semua registration','D'=>'Ubah nama unit menjadi OLD'],'correct'=>'B','explanation'=>'Inactive menjaga data historis sekaligus mengeluarkan unit dari operasi aktif.'],
            ['question'=>'Sebelum menonaktifkan unit, administrator sebaiknya?','options'=>['A'=>'Langsung nonaktifkan tanpa review','B'=>'Pastikan tidak ada proses kritis aktif dan pahami dampaknya','C'=>'Hapus user unit terlebih dahulu','D'=>'Reset semua opening'],'correct'=>'B','explanation'=>'Lifecycle change perlu mempertimbangkan proses yang masih berjalan.'],
            ['question'=>'Perubahan workflow, payment, selection, dan access control dikategorikan lebih berisiko karena?','options'=>['A'=>'Selalu mengubah CSS','B'=>'Dapat memengaruhi keputusan, data, dan jalur operasional','C'=>'Tidak dapat diuji','D'=>'Hanya Super Admin yang melihatnya'],'correct'=>'B','explanation'=>'Area tersebut dekat dengan integritas proses dan keputusan penerimaan.'],
            ['type'=>'tf','question'=>'Rollback code selalu cukup untuk memulihkan aplikasi setelah migration database bermasalah.','correct'=>false,'explanation'=>'Rollback code dan data/migration adalah masalah berbeda dan perlu strategi masing-masing.'],
            ['question'=>'Backup dinilai benar-benar berguna ketika?','options'=>['A'=>'File backup ada di server','B'=>'Ukuran file besar','C'=>'Proses restore telah diuji dan menghasilkan sistem yang dapat digunakan','D'=>'Backup dibuat manual'],'correct'=>'C','explanation'=>'Restore test membuktikan backup dapat dipakai saat insiden.'],
            ['question'=>'RPO terutama membantu menentukan?','options'=>['A'=>'Warna dashboard','B'=>'Seberapa banyak kehilangan data yang dapat ditoleransi','C'=>'Jumlah role','D'=>'Format sertifikat'],'correct'=>'B','explanation'=>'RPO berkaitan dengan toleransi kehilangan data terhadap titik pemulihan.'],
            ['question'=>'RTO berkaitan dengan?','options'=>['A'=>'Target waktu pemulihan layanan','B'=>'Jumlah data yang diarsipkan','C'=>'Jumlah pendaftar','D'=>'Role yang boleh export'],'correct'=>'A','explanation'=>'RTO adalah target waktu untuk memulihkan layanan.'],
            ['question'=>'Mengapa hard delete data operasional sebaiknya dihindari untuk sekadar merapikan dashboard?','options'=>['A'=>'Karena database tidak mendukung delete','B'=>'Karena lifecycle/archiving lebih menjaga histori dan audit','C'=>'Karena delete selalu gagal','D'=>'Karena data harus selalu public'],'correct'=>'B','explanation'=>'Lifecycle membantu operasi tetap rapi tanpa menghilangkan histori penting.'],
            ['question'=>'Current stage registration sebaiknya berubah melalui?','options'=>['A'=>'Edit langsung field database','B'=>'Business rule/workflow transition resmi','C'=>'Spreadsheet import manual','D'=>'Rename status'],'correct'=>'B','explanation'=>'Transition resmi menjaga prasyarat, konsistensi, dan audit.'],
            ['type'=>'tf','question'=>'Exception satu kasus sebaiknya langsung dijadikan bypass permanen di aplikasi.','correct'=>false,'explanation'=>'Exception harus diklasifikasikan dan tidak otomatis menjadi rule permanen.'],
            ['question'=>'Penetapan hasil dan publikasi hasil sebaiknya?','options'=>['A'=>'Selalu terjadi bersamaan tanpa review','B'=>'Dipisahkan agar keputusan dapat direview sebelum terlihat pendaftar','C'=>'Dilakukan oleh pendaftar','D'=>'Tidak perlu audit'],'correct'=>'B','explanation'=>'Pemisahan decision dan publication mengurangi risiko pengumuman prematur.'],
            ['question'=>'Jika hasil sudah tersimpan internal tetapi belum siap diumumkan, status yang tepat secara konsep adalah?','options'=>['A'=>'Tetap internal/draft sampai proses publish dilakukan','B'=>'Otomatis public','C'=>'Hapus hasil','D'=>'Ubah role pendaftar'],'correct'=>'A','explanation'=>'Menyimpan keputusan tidak identik dengan mempublikasikannya.'],
            ['question'=>'Bulk export lebih sensitif daripada melihat satu record karena?','options'=>['A'=>'File lebih berwarna','B'=>'Data keluar dari kontrol aplikasi dalam jumlah besar','C'=>'Export tidak bisa dihapus','D'=>'Selalu berisi password'],'correct'=>'B','explanation'=>'Setelah diunduh, kontrol akses aplikasi tidak lagi membatasi file tersebut.'],
            ['question'=>'Prinsip data minimization mendorong administrator untuk?','options'=>['A'=>'Mengumpulkan semua data yang mungkin berguna','B'=>'Mengambil dan menampilkan data yang benar-benar dibutuhkan untuk tujuan proses','C'=>'Menghapus audit log','D'=>'Menyembunyikan semua data dari staff'],'correct'=>'B','explanation'=>'Data minimization membatasi pengumpulan/penggunaan pada kebutuhan yang relevan.'],
            ['type'=>'tf','question'=>'Hak melihat record di aplikasi selalu berarti user juga harus mendapat hak bulk export.','correct'=>false,'explanation'=>'Bulk export membawa risiko tambahan dan dapat memerlukan kontrol lebih ketat.'],
            ['question'=>'Saat investigasi perubahan konfigurasi, sumber evidence teknis yang paling relevan adalah?','options'=>['A'=>'Perkiraan user','B'=>'Audit trail dengan actor, waktu, object, dan old/new value','C'=>'Screenshot homepage saja','D'=>'Chat grup informal'],'correct'=>'B','explanation'=>'Audit trail memberi rekaman perubahan yang terstruktur.'],
            ['type'=>'tf','question'=>'Audit log sebaiknya dapat diedit user agar kesalahan pencatatan dapat diperbaiki.','correct'=>false,'explanation'=>'Audit log perlu immutable pada jalur aplikasi agar tetap dapat dipercaya.'],
            ['question'=>'Consent snapshot penting karena?','options'=>['A'=>'Menghemat storage','B'=>'Membuktikan konten yang disetujui pada saat acceptance, meski teks saat ini berubah','C'=>'Menggantikan password','D'=>'Mempercepat queue'],'correct'=>'B','explanation'=>'Snapshot menjaga bukti historis dari perubahan konten berikutnya.'],
            ['question'=>'Langkah pertama yang tepat saat insiden data terdeteksi adalah?','options'=>['A'=>'Hapus semua log','B'=>'Contain dampak sambil menjaga evidence','C'=>'Matikan database permanen','D'=>'Publikasikan root cause sebelum investigasi'],'correct'=>'B','explanation'=>'Containment dan preservation of evidence adalah fondasi respons awal.'],
            ['question'=>'Dalam incident response, menentukan scope berarti?','options'=>['A'=>'Menentukan warna severity','B'=>'Menentukan data, user/unit, periode, dan sistem yang terdampak','C'=>'Menghapus semua data terkait','D'=>'Mengganti vendor'],'correct'=>'B','explanation'=>'Scope membantu menentukan dampak dan tindakan pemulihan.'],
            ['type'=>'tf','question'=>'Jika insiden terlihat kecil, evidence boleh dihapus setelah masalah tampak selesai.','correct'=>false,'explanation'=>'Evidence perlu dipertahankan untuk investigasi dan pembelajaran.'],
            ['question'=>'Troubleshooting yang baik dimulai dengan?','options'=>['A'=>'Restart semua service','B'=>'Reproduksi masalah dan kumpulkan evidence relevan','C'=>'Ubah permission menjadi 777','D'=>'Reinstall aplikasi'],'correct'=>'B','explanation'=>'Diagnosis mengurangi variabel dan mencegah perubahan acak.'],
            ['question'=>'Mixed content HTTP/HTTPS paling mungkin berkaitan dengan lapisan?','options'=>['A'=>'Rendering nilai tes','B'=>'URL/proxy/forwarded scheme atau konfigurasi aplikasi','C'=>'Question bank','D'=>'Role seeder'],'correct'=>'B','explanation'=>'Mixed content berkaitan dengan scheme URL yang dihasilkan aplikasi/proxy.'],
            ['question'=>'Jika email tercatat processed tetapi tidak diterima user, administrator sebaiknya membedakan?','options'=>['A'=>'PHP dan CSS','B'=>'Accepted/processed aplikasi dengan delivery provider akhir','C'=>'Unit dan pathway','D'=>'Draft dan archived'],'correct'=>'B','explanation'=>'Tidak adanya exception aplikasi tidak menjamin delivery sampai inbox.'],
            ['question'=>'Queue worker yang gagal memproses job sebaiknya ditelusuri melalui?','options'=>['A'=>'Audit visual halaman','B'=>'Worker status, logs, failed jobs, dan konfigurasi queue/provider','C'=>'Hapus semua job','D'=>'Ubah role user'],'correct'=>'B','explanation'=>'Observability queue diperlukan untuk mengetahui titik kegagalan.'],
            ['question'=>'Mengapa credential atau secret tidak seharusnya ikut dalam export konfigurasi biasa?','options'=>['A'=>'Akan memperbesar file','B'=>'Meningkatkan risiko penyebaran rahasia di luar mekanisme secret management','C'=>'Tidak bisa berupa text','D'=>'Akan mengubah theme'],'correct'=>'B','explanation'=>'Config portability harus memisahkan data konfigurasi dari secret.'],
            ['type'=>'tf','question'=>'Import konfigurasi ke unit target sebaiknya langsung dipublish tanpa review agar identik dengan sumber.','correct'=>false,'explanation'=>'Target dapat memiliki mode, data, atau kebutuhan berbeda sehingga perlu review.'],
            ['question'=>'Ketika perubahan konfigurasi bermasalah, rollback paling tepat ditentukan berdasarkan?','options'=>['A'=>'Siapa yang paling senior','B'=>'Apakah sumber masalah code, config, atau data','C'=>'Jumlah pengguna online','D'=>'Ukuran repository'],'correct'=>'B','explanation'=>'Jenis sumber masalah menentukan bentuk rollback yang aman.'],
            ['question'=>'Mengapa restore database penuh bukan pilihan pertama untuk salah konfigurasi kecil?','options'=>['A'=>'Karena restore tidak mungkin','B'=>'Dampaknya jauh lebih besar daripada masalah dan dapat menimpa data baru','C'=>'Karena config tidak tersimpan di database','D'=>'Karena hanya vendor yang boleh restore'],'correct'=>'B','explanation'=>'Recovery harus proporsional dan meminimalkan collateral damage.'],
            ['question'=>'Pada mode Higher Education, program studi dapat memengaruhi?','options'=>['A'=>'Hanya warna UI','B'=>'Konfigurasi dan pool tertentu yang scoped per program','C'=>'Password admin','D'=>'Audit retention'],'correct'=>'B','explanation'=>'Higher Education mendukung kebutuhan per program studi.'],
            ['type'=>'tf','question'=>'Fitur program studi harus selalu dipaksakan aktif pada mode K12.','correct'=>false,'explanation'=>'Fitur harus mengikuti mode dan kebutuhan operasional.'],
            ['question'=>'Jika unit direaktivasi setelah lama inactive, langkah aman adalah?','options'=>['A'=>'Langsung open semua opening lama','B'=>'Review konfigurasi/opening sebelum publikasi kembali','C'=>'Hapus histori lama','D'=>'Reset semua user'],'correct'=>'B','explanation'=>'Konfigurasi lama mungkin tidak lagi sesuai kondisi terkini.'],
            ['question'=>'Saat review akses berkala, fokus utama adalah?','options'=>['A'=>'Apakah user menyukai UI','B'=>'Apakah user aktif, role, dan unit masih sesuai tanggung jawab','C'=>'Apakah password pendek','D'=>'Apakah user sering login'],'correct'=>'B','explanation'=>'Access review memastikan hak tetap relevan dengan tugas.'],
            ['question'=>'Mengapa akun personal penting untuk audit?','options'=>['A'=>'Agar nama lebih pendek','B'=>'Agar actor pada audit dapat dikaitkan dengan individu yang bertanggung jawab','C'=>'Agar user bisa melihat unit lain','D'=>'Agar queue lebih cepat'],'correct'=>'B','explanation'=>'Identitas actor hanya bermakna jika credential tidak dibagi.'],
            ['question'=>'Jika user unit melihat data unit lain, prioritas administrator adalah?','options'=>['A'=>'Anggap normal karena staff internal','B'=>'Contain akses, kumpulkan evidence, dan periksa scope/authorization','C'=>'Hapus data unit lain','D'=>'Beri akses unit lain juga agar konsisten'],'correct'=>'B','explanation'=>'Cross-unit exposure adalah masalah authorization yang perlu segera ditangani.'],
            ['type'=>'tf','question'=>'Archived data boleh otomatis muncul kembali di operational view tanpa proses reaktivasi.','correct'=>false,'explanation'=>'Archived memisahkan histori dari data operasional aktif.'],
            ['question'=>'Saat monitoring penerimaan aktif, pola error berulang sebaiknya?','options'=>['A'=>'Ditangani sebagai kasus individual selamanya','B'=>'Dianalisis sebagai potensi masalah sistemik','C'=>'Diabaikan jika masih ada user yang berhasil','D'=>'Disembunyikan dari log'],'correct'=>'B','explanation'=>'Pola berulang dapat menunjukkan masalah konfigurasi atau aplikasi yang lebih luas.'],
            ['question'=>'Apa hubungan test suite dengan change management?','options'=>['A'=>'Tidak terkait','B'=>'Test suite memberi evidence regression sebelum/selama release','C'=>'Menggantikan seluruh UAT manusia','D'=>'Hanya untuk developer lokal'],'correct'=>'B','explanation'=>'Automated test membantu memastikan perubahan tidak merusak behavior existing.'],
            ['type'=>'tf','question'=>'Lulus test suite berarti seluruh proses bisnis production pasti aman tanpa review lain.','correct'=>false,'explanation'=>'Test suite penting tetapi tidak menggantikan review konfigurasi, infra, data, dan UAT.'],
            ['question'=>'Sebelum perubahan production berisiko tinggi, administrator sebaiknya memiliki?','options'=>['A'=>'Hanya screenshot sebelum perubahan','B'=>'Tujuan, impact assessment, testing, dan rollback path','C'=>'Akun baru','D'=>'Question bank terbaru'],'correct'=>'B','explanation'=>'Perubahan terkontrol membutuhkan pemahaman dampak dan jalur pemulihan.'],
            ['question'=>'Jika satu exception sering berulang, tindak lanjut terbaik adalah?','options'=>['A'=>'Terus bypass manual','B'=>'Analisis pola dan pertimbangkan perbaikan rule/workflow yang terkontrol','C'=>'Hapus kasus tersebut','D'=>'Beri semua staff Super Admin'],'correct'=>'B','explanation'=>'Exception berulang dapat menjadi sinyal rule atau workflow perlu diperbaiki.'],
            ['question'=>'Apa tujuan utama memisahkan operational view dari data inactive/archived?','options'=>['A'=>'Mengurangi ukuran database otomatis','B'=>'Memfokuskan pekerjaan harian tanpa menghilangkan histori','C'=>'Menghapus kewajiban audit','D'=>'Menyembunyikan error'],'correct'=>'B','explanation'=>'Pemisahan lifecycle memperjelas operasi sambil menjaga data historis.'],
            ['question'=>'Pada recovery setelah insiden, langkah penutup yang penting adalah?','options'=>['A'=>'Menghapus tiket','B'=>'Verifikasi fungsi kritis dan dokumentasikan tindakan korektif','C'=>'Mengganti seluruh user','D'=>'Memindahkan semua data ke export'],'correct'=>'B','explanation'=>'Recovery perlu validation dan lessons learned agar insiden tidak berulang.'],
        ];

        $this->seedQuestionBank($program, 'sca-v1', $questions);
    }
}
