<?php

namespace Database\Seeders\Training\Certification;

use App\Models\CertificationProgram;
use Database\Seeders\Training\CurriculumSeeder;

class AdmissionOperatorCertificationSeeder extends CurriculumSeeder
{
    public function run(): void
    {
        $program = CertificationProgram::query()->where('code', 'SCAO')->where('version', '1.0')->firstOrFail();

        $q = [
            ['question'=>'Tugas utama TU/operator dalam SPMB adalah?','options'=>['A'=>'Mendesain kebijakan penerimaan','B'=>'Menjalankan verifikasi dan operasi harian sesuai workflow unit','C'=>'Mengelola seluruh server','D'=>'Mengubah role staff'],'correct'=>'B','explanation'=>'TU menjalankan proses operasional yang sudah dikonfigurasi.'],
            ['type'=>'tf','question'=>'TU boleh mengubah konfigurasi unit jika diperlukan agar satu pendaftar dapat lolos.','correct'=>false,'explanation'=>'Perubahan konfigurasi berada di luar scope normal TU dan harus dieskalasikan.'],
            ['question'=>'Sebelum memverifikasi sebuah registration, TU sebaiknya?','options'=>['A'=>'Langsung klik verify','B'=>'Periksa identity, current stage, dan requirement yang sedang diproses','C'=>'Ubah stage ke completed','D'=>'Reset password pendaftar'],'correct'=>'B','explanation'=>'State dan requirement harus dipahami sebelum mengambil tindakan.'],
            ['question'=>'Jika masalah berada di luar kewenangan TU, tindakan terbaik adalah?','options'=>['A'=>'Mencari workaround sendiri','B'=>'Eskalasi dengan registration, waktu, langkah reproduksi, dan evidence relevan','C'=>'Menghapus data','D'=>'Meminta pendaftar membuat akun baru'],'correct'=>'B','explanation'=>'Eskalasi yang baik membawa konteks yang cukup untuk diagnosis.'],
            ['question'=>'Validasi data pendaftar berarti?','options'=>['A'=>'Mengubah data agar terlihat rapi','B'=>'Memeriksa konsistensi dan kecukupan data berdasarkan evidence/SOP','C'=>'Menghapus field kosong','D'=>'Menyetujui semua data'],'correct'=>'B','explanation'=>'Validasi adalah pemeriksaan, bukan pembenaran data tanpa dasar.'],
            ['type'=>'tf','question'=>'Mismatch kecil pada identitas boleh diabaikan selama dokumen lain lengkap.','correct'=>false,'explanation'=>'Mismatch perlu diperiksa karena dapat memengaruhi integritas data.'],
            ['question'=>'Koreksi data pendaftar sebaiknya dilakukan berdasarkan?','options'=>['A'=>'Perkiraan operator','B'=>'Evidence atau prosedur koreksi yang dapat dipertanggungjawabkan','C'=>'Pesan lisan tanpa identitas','D'=>'Keinginan agar antrian cepat selesai'],'correct'=>'B','explanation'=>'Koreksi harus traceable.'],
            ['question'=>'Jika field sudah verified dan pendaftar meminta perubahan, TU sebaiknya?','options'=>['A'=>'Ubah langsung tanpa bukti','B'=>'Periksa evidence dan ikuti prosedur koreksi/eskalasi','C'=>'Hapus registration','D'=>'Buat akun baru'],'correct'=>'B','explanation'=>'Data verified perlu perlakuan lebih hati-hati.'],
            ['type'=>'tf','question'=>'Data orang tua/wali boleh disalin ke perangkat pribadi untuk memudahkan komunikasi.','correct'=>false,'explanation'=>'Salinan pribadi meningkatkan risiko dan umumnya tidak diperlukan.'],
            ['question'=>'Dokumen uploaded berstatus pending berarti?','options'=>['A'=>'Sudah valid','B'=>'File tersedia tetapi belum diputuskan verified/rejected','C'=>'Sudah rejected','D'=>'Tidak dapat dilihat'],'correct'=>'B','explanation'=>'Upload bukan bukti validitas.'],
            ['question'=>'Alasan reject dokumen yang baik adalah?','options'=>['A'=>'Salah','B'=>'Dokumen buram pada halaman identitas; unggah ulang file yang terbaca','C'=>'Tidak sesuai','D'=>'Ulangi lagi'],'correct'=>'B','explanation'=>'Reason harus actionable.'],
            ['type'=>'tf','question'=>'Dokumen applicant sebaiknya dipindahkan ke folder public agar lebih mudah dibuka.','correct'=>false,'explanation'=>'Dokumen perlu tetap private dan melalui authorization.'],
            ['question'=>'Jika file applicant mencurigakan atau gagal diproses, TU sebaiknya?','options'=>['A'=>'Jalankan file di komputer pribadi','B'=>'Jangan eksekusi; gunakan jalur resmi dan eskalasi bila perlu','C'=>'Upload ke public drive','D'=>'Ubah extension'],'correct'=>'B','explanation'=>'File applicant diperlakukan sebagai untrusted content.'],
            ['question'=>'Dokumen yang sudah verified seharusnya?','options'=>['A'=>'Diminta upload ulang setiap hari','B'=>'Tidak diminta reupload kecuali ada alasan/prosedur yang jelas','C'=>'Dihapus','D'=>'Dipindahkan ke chat'],'correct'=>'B','explanation'=>'Verified state perlu dihormati dan perubahan harus beralasan.'],
            ['question'=>'Payment verification terutama didasarkan pada?','options'=>['A'=>'Dokumen akademik','B'=>'Evidence pembayaran, amount/reference, dan status yang sesuai','C'=>'Kecepatan pendaftar','D'=>'Jumlah sibling'],'correct'=>'B','explanation'=>'Payment diverifikasi berdasarkan evidence finansial.'],
            ['type'=>'tf','question'=>'Jika pembayaran belum cocok, TU boleh verify dulu agar pendaftar bisa lanjut lalu diperbaiki nanti.','correct'=>false,'explanation'=>'Status harus mencerminkan kondisi aktual.'],
            ['question'=>'Jika bukti pembayaran tidak terbaca, tindakan yang tepat adalah?','options'=>['A'=>'Verify berdasarkan asumsi','B'=>'Reject/minta perbaikan dengan alasan jelas atau eskalasi sesuai SOP','C'=>'Hapus payment','D'=>'Ubah nominal'],'correct'=>'B','explanation'=>'Evidence tidak memadai tidak boleh dipaksakan valid.'],
            ['question'=>'Virtual Account yang sudah terasosiasi dengan registration sebaiknya?','options'=>['A'=>'Dipakai juga oleh applicant lain','B'=>'Diperlakukan sesuai assignment dan tidak dipinjam sembarangan','C'=>'Diubah manual setiap hari','D'=>'Dibagikan ke grup'],'correct'=>'B','explanation'=>'Assignment VA harus konsisten.'],
            ['question'=>'TU menerima screenshot transfer melalui WhatsApp. Apa yang harus dilakukan?','options'=>['A'=>'Anggap otomatis verified','B'=>'Gunakan informasi itu sebagai konteks tetapi keputusan tetap melalui record/prosedur resmi','C'=>'Hapus record payment aplikasi','D'=>'Kirim screenshot ke semua staff'],'correct'=>'B','explanation'=>'Kanal komunikasi bukan pengganti record aplikasi.'],
            ['question'=>'Test session berbeda dari test karena?','options'=>['A'=>'Session memuat waktu/kapasitas pelaksanaan','B'=>'Tidak ada beda','C'=>'Session hanya untuk admin','D'=>'Test tidak punya nama'],'correct'=>'A','explanation'=>'Session adalah instance pelaksanaan test.'],
            ['type'=>'tf','question'=>'TU boleh menjanjikan slot tes di luar kapasitas sistem selama pendaftar datang lebih awal.','correct'=>false,'explanation'=>'Kapasitas harus mengikuti data session yang dikelola.'],
            ['question'=>'Jika session penuh, TU sebaiknya?','options'=>['A'=>'Masukkan peserta secara manual melewati kapasitas','B'=>'Cari opsi tersedia atau eskalasi perubahan kapasitas ke Admin Unit','C'=>'Hapus booking orang lain','D'=>'Ubah tanggal lahir'],'correct'=>'B','explanation'=>'TU mengoperasikan kapasitas yang tersedia, bukan membuat kebijakan baru.'],
            ['question'=>'Kartu tes sebaiknya dibuat dari?','options'=>['A'=>'File Word manual','B'=>'Route/output resmi yang membaca registration dan session aktual','C'=>'Screenshot kartu peserta lain','D'=>'Template chat'],'correct'=>'B','explanation'=>'Dokumen cetak harus mencerminkan state aplikasi.'],
            ['type'=>'tf','question'=>'TU boleh mengedit manual PDF kartu tes setelah diunduh agar data terlihat sesuai.','correct'=>false,'explanation'=>'Perbaikan harus dilakukan pada data sumber/prosedur yang benar.'],
            ['question'=>'Input hasil tes berbeda dari keputusan seleksi karena?','options'=>['A'=>'Hasil tes adalah evidence; accepted/rejected adalah keputusan proses seleksi','B'=>'Tidak berbeda','C'=>'Hasil tes hanya untuk Admin Pusat','D'=>'Seleksi tidak menggunakan data'],'correct'=>'A','explanation'=>'Operator harus memisahkan pencatatan evidence dari keputusan.'],
            ['question'=>'Jika salah input nilai tes ditemukan setelah disimpan, TU sebaiknya?','options'=>['A'=>'Ubah diam-diam tanpa evidence','B'=>'Konfirmasi sumber nilai dan lakukan koreksi/eskalasi yang traceable','C'=>'Hapus applicant','D'=>'Biarkan selalu'],'correct'=>'B','explanation'=>'Koreksi hasil perlu evidence dan jejak.'],
            ['type'=>'tf','question'=>'TU boleh mengubah nilai agar selaras dengan keputusan accepted yang sudah disampaikan orang lain.','correct'=>false,'explanation'=>'Evidence tidak boleh disesuaikan untuk membenarkan keputusan.'],
            ['question'=>'No-show test sebaiknya?','options'=>['A'=>'Diperlakukan sesuai state/prosedur no-show yang berlaku','B'=>'Diberi nilai rata-rata tanpa aturan','C'=>'Dihapus registration-nya','D'=>'Dianggap lulus'],'correct'=>'A','explanation'=>'Exception tetap harus mengikuti proses resmi.'],
            ['question'=>'Saat pendaftar meminta bypass karena deadline, TU sebaiknya?','options'=>['A'=>'Paksa stage lanjut','B'=>'Jelaskan requirement aktual dan eskalasi pengecualian kebijakan bila perlu','C'=>'Ubah role pendaftar','D'=>'Hapus requirement'],'correct'=>'B','explanation'=>'Tekanan waktu tidak menghapus requirement.'],
            ['question'=>'Jawaban layanan pendaftar sebaiknya berbasis?','options'=>['A'=>'Ingatan operator','B'=>'State aktual registration dan informasi resmi','C'=>'Rumor grup','D'=>'Status applicant lain'],'correct'=>'B','explanation'=>'Support harus faktual dan konsisten.'],
            ['type'=>'tf','question'=>'TU boleh menjanjikan hasil seleksi sebelum publikasi resmi jika sudah mendengar informasi internal.','correct'=>false,'explanation'=>'Informasi internal belum tentu final/published.'],
            ['question'=>'Penggunaan WhatsApp yang aman adalah?','options'=>['A'=>'Mengirim semua dokumen applicant ke grup','B'=>'Mengirim informasi seperlunya dan mengarahkan tindakan penting kembali ke aplikasi','C'=>'Menyimpan seluruh kontak untuk kebutuhan pribadi','D'=>'Menggunakan chat sebagai approval final'],'correct'=>'B','explanation'=>'Kanal komunikasi harus meminimalkan data dan tidak menggantikan record.'],
            ['question'=>'Jika pendaftar mengirim NIK di grup umum, TU sebaiknya?','options'=>['A'=>'Meneruskan ke grup lain','B'=>'Arahkan ke kanal yang sesuai dan minimalkan penyebaran data','C'=>'Simpan screenshot','D'=>'Publikasikan agar tim tahu'],'correct'=>'B','explanation'=>'Data identitas harus dibatasi penyebarannya.'],
            ['type'=>'tf','question'=>'Need-to-know berarti TU boleh membuka data apa pun selama masih di unit yang sama.','correct'=>false,'explanation'=>'Akses tetap harus berkaitan dengan tugas yang sedang dilakukan.'],
            ['question'=>'Mengapa akun TU harus personal?','options'=>['A'=>'Agar audit actor dapat dipercaya dan credential tidak dibagi','B'=>'Agar bisa melihat unit lain','C'=>'Agar export lebih cepat','D'=>'Agar role tidak diperlukan'],'correct'=>'A','explanation'=>'Accountability bergantung pada identitas akun.'],
            ['question'=>'Saat pergantian shift, handover yang benar adalah?','options'=>['A'=>'Berikan password akun','B'=>'Serahkan konteks kasus outstanding melalui kanal resmi','C'=>'Biarkan browser tetap login untuk petugas berikut','D'=>'Ubah nama akun'],'correct'=>'B','explanation'=>'Handover memindahkan pekerjaan, bukan credential.'],
            ['question'=>'Jika TU melihat data unit lain, tindakan pertama yang tepat adalah?','options'=>['A'=>'Export sebagai bukti','B'=>'Hentikan akses yang tidak diperlukan dan laporkan sebagai masalah authorization','C'=>'Bantu unit lain','D'=>'Ubah datanya agar sesuai'],'correct'=>'B','explanation'=>'Cross-unit visibility harus segera dieskalasikan.'],
            ['type'=>'tf','question'=>'Screenshot error boleh selalu dikirim apa adanya meski berisi data pribadi lengkap.','correct'=>false,'explanation'=>'Evidence harus cukup tetapi tetap meminimalkan paparan data.'],
            ['question'=>'Eskalasi yang baik minimal memuat?','options'=>['A'=>'“Error, tolong cek”','B'=>'Kasus/registration, waktu, langkah yang dilakukan, dan gejala/error relevan','C'=>'Password user','D'=>'Semua data unit'],'correct'=>'B','explanation'=>'Context yang jelas mempercepat diagnosis.'],
            ['question'=>'Self-check sebelum klik verify sebaiknya mencakup?','options'=>['A'=>'Applicant, object, evidence, dan keputusan','B'=>'Theme aplikasi','C'=>'Jumlah tab browser','D'=>'Nama admin lain'],'correct'=>'A','explanation'=>'Micro-check mencegah keputusan pada record yang salah.'],
            ['type'=>'tf','question'=>'Saat volume tinggi, bekerja dengan banyak tab tanpa mengecek identitas tidak menambah risiko kesalahan.','correct'=>false,'explanation'=>'Context switching dan banyak tab meningkatkan risiko salah record.'],
            ['question'=>'Jika antrian belum selesai pada akhir shift, TU sebaiknya?','options'=>['A'=>'Verify semuanya agar kosong','B'=>'Kelompokkan status dan handover kasus outstanding dengan jelas','C'=>'Hapus kasus sulit','D'=>'Ubah menjadi completed'],'correct'=>'B','explanation'=>'State harus tetap menggambarkan kenyataan.'],
            ['question'=>'Kasus menunggu perbaikan pendaftar sebaiknya?','options'=>['A'=>'Dipaksa selesai','B'=>'Dibiarkan pada status yang mencerminkan menunggu dengan catatan/reason yang jelas','C'=>'Dihapus','D'=>'Dipindah unit'],'correct'=>'B','explanation'=>'Operational state harus jujur terhadap kondisi aktual.'],
            ['question'=>'Jika dokumen valid tetapi pembayaran invalid, registration sebaiknya?','options'=>['A'=>'Dilanjutkan melewati payment karena dokumen sudah benar','B'=>'Tetap mengikuti requirement payment sampai valid','C'=>'Ditandai completed','D'=>'Dihapus'],'correct'=>'B','explanation'=>'Setiap requirement harus dipenuhi sesuai workflow.'],
            ['question'=>'Jika pembayaran valid tetapi KK invalid, tindakan yang benar adalah?','options'=>['A'=>'Verify keduanya','B'=>'Verify payment dan reject KK berdasarkan evidence masing-masing','C'=>'Reject semuanya','D'=>'Tidak usah mencatat'],'correct'=>'B','explanation'=>'Keputusan tiap domain mengikuti evidence masing-masing.'],
            ['type'=>'tf','question'=>'Keputusan satu resource boleh otomatis dipakai untuk membenarkan resource lain yang berbeda.','correct'=>false,'explanation'=>'Dokumen, payment, test, dan data memiliki evidence terpisah.'],
            ['question'=>'Jika document requirement tidak muncul padahal seharusnya wajib, TU sebaiknya?','options'=>['A'=>'Buat requirement sendiri','B'=>'Eskalasi konfigurasi ke Admin Unit dengan contoh kasus','C'=>'Verify tanpa dokumen','D'=>'Hapus registration'],'correct'=>'B','explanation'=>'TU tidak mendesain requirement.'],
            ['question'=>'Jika pendaftar tidak menerima email tetapi aplikasi mencatat notifikasi dibuat, TU sebaiknya?','options'=>['A'=>'Menjamin email pasti masuk','B'=>'Catat kasus dan eskalasi delivery/queue bila diperlukan; berikan jalur resmi alternatif yang tersedia','C'=>'Ubah email sembarangan','D'=>'Hapus notifikasi'],'correct'=>'B','explanation'=>'Status aplikasi tidak selalu sama dengan delivery provider.'],
            ['question'=>'Alasan utama tidak menyimpan dokumen applicant di laptop pribadi adalah?','options'=>['A'=>'File besar','B'=>'Menambah salinan dan risiko akses di luar kontrol aplikasi','C'=>'Tidak dapat dibuka','D'=>'Mengurangi kecepatan internet'],'correct'=>'B','explanation'=>'Salinan lokal memperluas attack surface.'],
            ['type'=>'tf','question'=>'Jika operator yakin file aman, macro/attachment dari applicant boleh dijalankan di komputer kerja.','correct'=>false,'explanation'=>'File applicant tetap untrusted dan tidak boleh dieksekusi sembarangan.'],
            ['question'=>'Ketika salah record terverifikasi, TU sebaiknya?','options'=>['A'=>'Sembunyikan kesalahan','B'=>'Segera hentikan dampak lanjutan dan eskalasi koreksi dengan evidence','C'=>'Hapus audit log','D'=>'Ubah record lain agar sama'],'correct'=>'B','explanation'=>'Kesalahan operasional perlu containment dan koreksi traceable.'],
            ['question'=>'Apa indikator TU bekerja sesuai governance?','options'=>['A'=>'Antrian selalu nol meski banyak bypass','B'=>'Keputusan konsisten dengan evidence, scope, workflow, dan dapat diaudit','C'=>'Semua applicant di-verify','D'=>'Tidak pernah eskalasi'],'correct'=>'B','explanation'=>'Kualitas lebih penting daripada sekadar kecepatan.'],
            ['question'=>'Pada happy path pemilihan jadwal tes, siapa yang menyelesaikan pilihan seluruh sesi wajib dan konfirmasi final?','options'=>['A'=>'Pendaftar sendiri melalui portal','B'=>'TU selalu memilihkan','C'=>'Super Admin','D'=>'Sistem tanpa interaksi pengguna'],'correct'=>'A','explanation'=>'Alur normal memberi kendali kepada pendaftar untuk memilih seluruh tes wajib dan mengonfirmasi jadwal.'],
            ['question'=>'Jika peserta baru memilih 1 dari 3 tes wajib, TU sebaiknya?','options'=>['A'=>'Anggap selesai karena satu booking sudah ada','B'=>'Arahkan peserta melengkapi dua tes wajib yang tersisa lalu konfirmasi','C'=>'Cetak kartu tes manual','D'=>'Pindahkan ke selection'],'correct'=>'B','explanation'=>'Semua tes wajib harus memiliki sesi sebelum jadwal dapat dikonfirmasi.'],
            ['type'=>'tf','question'=>'Kartu tes boleh diberikan sebelum jadwal dikonfirmasi asalkan semua sesi terlihat di layar.','correct'=>false,'explanation'=>'Kartu tes hanya tersedia setelah seluruh jadwal wajib lengkap dan dikonfirmasi.'],
            ['question'=>'Jika sesi yang dipilih peserta dibatalkan, tindakan yang benar adalah?','options'=>['A'=>'Biarkan kartu lama berlaku','B'=>'Peserta memilih sesi baru lalu melakukan konfirmasi ulang','C'=>'Paksa masuk sesi penuh','D'=>'Ubah hasil tes menjadi exempted'],'correct'=>'B','explanation'=>'Pembatalan sesi melepaskan booking dan membutuhkan rebooking serta rekonfirmasi.'],
            ['question'=>'TU menemukan data registration yang tampaknya berasal dari prefill Terusan tetapi salah. Apa yang paling tepat?','options'=>['A'=>'Minta akses Resource Terusan lalu edit master sendiri','B'=>'Tangani evidence pada registration dan eskalasi sumber master ke Admin Unit bila perlu','C'=>'Hapus registration','D'=>'Ubah identitas tanpa bukti'],'correct'=>'B','explanation'=>'Master Terusan dikelola Admin Unit; TU tetap bekerja pada scope operasional registration.'],
            ['type'=>'tf','question'=>'TU boleh menggunakan file master Terusan untuk troubleshooting rutin selama masih satu unit.','correct'=>false,'explanation'=>'TU tidak memiliki akses normal ke Resource Terusan; troubleshooting harus meminimalkan paparan data dan mengikuti scope.'],
        ];

        $this->seedQuestionBank($program, 'scao-v1', $q);
    }
}
