<?php

namespace Database\Seeders\Training\Certification;

use App\Models\CertificationProgram;
use Database\Seeders\Training\CurriculumSeeder;

class UnitAdministratorCertificationSeeder extends CurriculumSeeder
{
    public function run(): void
    {
        $program = CertificationProgram::query()->where('code', 'SCUA')->firstOrFail();

        $q = [
            ['question'=>'Tanggung jawab utama Admin Unit adalah?','options'=>['A'=>'Mengelola seluruh deployment lintas unit','B'=>'Mengelola konfigurasi dan operasi penerimaan pada unitnya','C'=>'Mengelola server Linux','D'=>'Menjadi pendaftar cadangan'],'correct'=>'B','explanation'=>'Admin Unit memiliki kewenangan pada konfigurasi dan operasi unitnya.'],
            ['type'=>'tf','question'=>'Admin Unit sebaiknya menggunakan akun Super Admin untuk pekerjaan rutin agar semua menu tersedia.','correct'=>false,'explanation'=>'Pekerjaan rutin harus dilakukan dengan role yang sesuai scope.'],
            ['question'=>'Sebelum mengubah konfigurasi karena angka dashboard terlihat aneh, Admin Unit sebaiknya?','options'=>['A'=>'Langsung reset konfigurasi','B'=>'Telusuri data sumber dan konteks opening/status','C'=>'Hapus data hari ini','D'=>'Nonaktifkan unit'],'correct'=>'B','explanation'=>'Dashboard adalah ringkasan; keputusan perlu verifikasi data sumber.'],
            ['question'=>'Masalah yang menyangkut konfigurasi global sebaiknya?','options'=>['A'=>'Diubah sendiri oleh TU','B'=>'Dieskalasikan ke Super Admin dengan evidence','C'=>'Dibiarkan selamanya','D'=>'Diselesaikan dengan hard delete'],'correct'=>'B','explanation'=>'Scope global berada di luar kewenangan normal Admin Unit.'],
            ['question'=>'Profil penerimaan sebaiknya diperiksa pada?','options'=>['A'=>'Panel admin saja','B'=>'Tampilan pendaftar/public setelah perubahan','C'=>'Database saja','D'=>'Email saja'],'correct'=>'B','explanation'=>'Konten public perlu diverifikasi pada surface yang benar-benar dilihat pendaftar.'],
            ['type'=>'tf','question'=>'Rich text yang terlihat benar di editor tidak perlu dicek lagi di UI pendaftar.','correct'=>false,'explanation'=>'Rendering pada sisi pendaftar tetap perlu diverifikasi.'],
            ['question'=>'Konten persetujuan sebaiknya?','options'=>['A'=>'Ambigu dan singkat','B'=>'Jelas, dapat dibaca, dan konsisten dengan proses','C'=>'Hanya berupa judul','D'=>'Diubah setelah acceptance tanpa jejak'],'correct'=>'B','explanation'=>'Persetujuan harus dapat dipahami dan dibuktikan.'],
            ['question'=>'Mengapa snapshot consent penting?','options'=>['A'=>'Agar modal lebih cepat','B'=>'Agar konten yang disetujui saat itu tetap dapat dibuktikan','C'=>'Agar user tidak bisa logout','D'=>'Agar unit aktif'],'correct'=>'B','explanation'=>'Snapshot menjaga bukti konten historis.'],
            ['question'=>'Status yang tepat saat opening masih disiapkan dan belum boleh menerima pendaftar adalah?','options'=>['A'=>'open','B'=>'draft','C'=>'closed','D'=>'archived'],'correct'=>'B','explanation'=>'Draft digunakan saat konfigurasi belum siap dipublikasikan.'],
            ['question'=>'Status paused paling tepat digunakan ketika?','options'=>['A'=>'Periode selesai permanen','B'=>'Penerimaan perlu dihentikan sementara tetapi dapat dilanjutkan','C'=>'Data harus dihapus','D'=>'Unit harus diarsipkan'],'correct'=>'B','explanation'=>'Pause adalah penghentian sementara.'],
            ['type'=>'tf','question'=>'Paused dan closed memiliki makna operasional yang sama.','correct'=>false,'explanation'=>'Paused sementara; closed menandai penerimaan ditutup.'],
            ['question'=>'Opening yang sudah selesai dan tidak lagi operasional tetapi histori tetap diperlukan sebaiknya?','options'=>['A'=>'archived','B'=>'open','C'=>'scheduled','D'=>'deleted'],'correct'=>'A','explanation'=>'Archived memisahkan histori dari operasi aktif.'],
            ['question'=>'Sebelum membuka opening, Admin Unit perlu memastikan?','options'=>['A'=>'Hanya logo sudah tampil','B'=>'Tanggal, form, requirement, workflow, payment/test, dan informasi public telah direview','C'=>'Semua user menjadi admin','D'=>'Semua data lama dihapus'],'correct'=>'B','explanation'=>'Go-live harus memvalidasi komponen penting end-to-end.'],
            ['question'=>'Jalur pendaftaran terutama berguna untuk?','options'=>['A'=>'Mengganti role','B'=>'Membedakan aturan/kelompok penerimaan yang memang berbeda','C'=>'Menghapus unit','D'=>'Mengatur theme'],'correct'=>'B','explanation'=>'Pathway merepresentasikan variasi proses atau kebijakan penerimaan.'],
            ['type'=>'tf','question'=>'Mengganti nama/kode jalur existing selalu aman walaupun sudah ada pendaftar.','correct'=>false,'explanation'=>'Perubahan pada object yang sudah digunakan perlu melihat dampak ke data existing.'],
            ['question'=>'Program studi terutama relevan pada mode?','options'=>['A'=>'K12 saja','B'=>'Higher Education atau Mixed sesuai konfigurasi','C'=>'Semua mode tanpa pengecualian','D'=>'Tidak pernah relevan'],'correct'=>'B','explanation'=>'Program studi adalah fitur yang relevan untuk Higher Education/Mixed.'],
            ['question'=>'Custom field sebaiknya ditambahkan ketika?','options'=>['A'=>'Ada kebutuhan data yang jelas dan belum diwakili field inti','B'=>'Agar form terlihat panjang','C'=>'Semua field inti sudah cukup','D'=>'Hanya untuk testing production'],'correct'=>'A','explanation'=>'Custom field harus memiliki tujuan dan menghindari duplikasi.'],
            ['type'=>'tf','question'=>'Data yang mungkin berguna di masa depan sebaiknya selalu dikumpulkan sekarang.','correct'=>false,'explanation'=>'Data minimization membatasi pengumpulan pada kebutuhan nyata.'],
            ['question'=>'Saat field form sudah memiliki data existing, perubahan besar sebaiknya?','options'=>['A'=>'Dilakukan tanpa review','B'=>'Dianalisis backward compatibility dan dampaknya ke data existing','C'=>'Menghapus semua registration','D'=>'Mengganti unit'],'correct'=>'B','explanation'=>'Form change dapat menjadi migration data/process.'],
            ['question'=>'Workflow unit sebaiknya dirancang berdasarkan?','options'=>['A'=>'Urutan menu di sidebar','B'=>'Proses nyata dan kebijakan unit','C'=>'Jumlah user admin','D'=>'Warna status'],'correct'=>'B','explanation'=>'Workflow harus merepresentasikan business process.'],
            ['question'=>'Tahapan pendaftaran di UI pendaftar bertujuan utama untuk?','options'=>['A'=>'Menambah jumlah card','B'=>'Memberi konteks posisi proses dan next action','C'=>'Menggantikan audit log','D'=>'Menentukan role'],'correct'=>'B','explanation'=>'Tahapan membantu pendaftar memahami posisi dan langkah berikutnya.'],
            ['type'=>'tf','question'=>'Semua blok informasi sebaiknya selalu tampil sekaligus agar pendaftar melihat semuanya.','correct'=>false,'explanation'=>'Prioritas informasi harus mengikuti stage dan relevansi.'],
            ['question'=>'Jika workflow diubah saat banyak pendaftar aktif, langkah pertama adalah?','options'=>['A'=>'Hapus stage lama','B'=>'Inventaris stage aktif dan dampak terhadap registration existing','C'=>'Paksa semua ke completed','D'=>'Nonaktifkan semua user'],'correct'=>'B','explanation'=>'Workflow change perlu impact analysis.'],
            ['question'=>'Current stage sebaiknya berubah melalui?','options'=>['A'=>'Business rule dan transition resmi','B'=>'Edit SQL langsung','C'=>'Spreadsheet tanpa validasi','D'=>'Rename label'],'correct'=>'A','explanation'=>'Transition resmi menjaga konsistensi dan audit.'],
            ['question'=>'Dokumen wajib sebaiknya ditentukan berdasarkan?','options'=>['A'=>'Semua dokumen yang mungkin dimiliki pendaftar','B'=>'Kebutuhan proses unit yang nyata','C'=>'Ukuran storage','D'=>'Preferensi TU pribadi'],'correct'=>'B','explanation'=>'Requirement harus minimal dan relevan.'],
            ['question'=>'Dokumen pendaftar seharusnya disimpan?','options'=>['A'=>'Di disk public tanpa authorization','B'=>'Secara private dan diakses melalui authorization','C'=>'Di chat admin','D'=>'Di spreadsheet'],'correct'=>'B','explanation'=>'Dokumen applicant perlu private storage dan kontrol akses.'],
            ['type'=>'tf','question'=>'Dokumen yang sudah verified boleh selalu diminta upload ulang tanpa alasan.','correct'=>false,'explanation'=>'Reupload perlu alasan yang jelas dan sesuai workflow.'],
            ['question'=>'Alasan reject dokumen yang baik adalah?','options'=>['A'=>'Salah','B'=>'File buram, halaman identitas tidak terbaca; unggah ulang file yang jelas','C'=>'Ulangi','D'=>'Tidak suka'],'correct'=>'B','explanation'=>'Reason harus actionable dan membantu pendaftar memperbaiki.'],
            ['question'=>'Virtual Account pool perlu dijaga agar?','options'=>['A'=>'Nomor dapat dipakai lintas semua unit tanpa aturan','B'=>'Assignment sesuai scope unit/program dan tidak terjadi peminjaman tidak sah','C'=>'Semua nomor sama','D'=>'Tidak perlu audit'],'correct'=>'B','explanation'=>'VA adalah resource yang perlu assignment konsisten.'],
            ['question'=>'Payment verification seharusnya dilakukan ketika?','options'=>['A'=>'Pendaftar meminta cepat','B'=>'Evidence dan status/nominal yang diperlukan sesuai','C'=>'Dokumen sudah lengkap','D'=>'Tes sudah dibuat'],'correct'=>'B','explanation'=>'Payment diverifikasi berdasarkan evidence finansial.'],
            ['type'=>'tf','question'=>'Jika pendaftar mengirim bukti lewat WhatsApp, Admin Unit boleh melewati record pembayaran aplikasi.','correct'=>false,'explanation'=>'Kanal komunikasi tidak menggantikan record operasional resmi.'],
            ['question'=>'Test dan test session berbeda karena?','options'=>['A'=>'Tidak berbeda','B'=>'Test mendefinisikan aktivitas, session mendefinisikan waktu/kapasitas pelaksanaan','C'=>'Session hanya untuk admin','D'=>'Test hanya untuk K12'],'correct'=>'B','explanation'=>'Session adalah instance pelaksanaan test.'],
            ['question'=>'Kapasitas sesi penting untuk?','options'=>['A'=>'Menentukan logo','B'=>'Mencegah overbooking dan menjaga resource pelaksanaan','C'=>'Mengubah role','D'=>'Menghapus jadwal'],'correct'=>'B','explanation'=>'Kapasitas merepresentasikan resource terbatas.'],
            ['type'=>'tf','question'=>'Jika slot terakhir dipilih dua pendaftar bersamaan, cukup mengandalkan urutan tampilan browser.','correct'=>false,'explanation'=>'Concurrency perlu kontrol transaksi/locking pada aplikasi.'],
            ['question'=>'Perubahan jadwal setelah banyak booking memerlukan?','options'=>['A'=>'Hanya edit tanggal','B'=>'Identifikasi peserta terdampak, perubahan resmi, dan komunikasi','C'=>'Hapus booking','D'=>'Buat unit baru'],'correct'=>'B','explanation'=>'Reschedule memiliki dampak data dan komunikasi.'],
            ['question'=>'Sebelum proses seleksi, Admin Unit sebaiknya?','options'=>['A'=>'Pastikan populasi dan data pendukung siap','B'=>'Langsung publish','C'=>'Hapus data incomplete','D'=>'Ubah semua status menjadi accepted'],'correct'=>'A','explanation'=>'Selection memerlukan input yang lengkap dan populasi jelas.'],
            ['question'=>'Batch seleksi berguna untuk?','options'=>['A'=>'Mengganti password massal','B'=>'Mengelola kelompok keputusan/proses seleksi','C'=>'Menghapus user','D'=>'Mengatur PWA'],'correct'=>'B','explanation'=>'Batch membantu grouping keputusan.'],
            ['question'=>'Penetapan hasil berbeda dari publikasi karena?','options'=>['A'=>'Penetapan adalah keputusan internal, publikasi membuat hasil terlihat pendaftar','B'=>'Tidak ada beda','C'=>'Publikasi hanya backup','D'=>'Penetapan hanya untuk TU'],'correct'=>'A','explanation'=>'Decision dan publication perlu dipisahkan.'],
            ['type'=>'tf','question'=>'Menyimpan hasil accepted otomatis berarti aman untuk langsung terlihat pendaftar.','correct'=>false,'explanation'=>'Hasil internal masih perlu review/publish.'],
            ['question'=>'Waiting list berarti?','options'=>['A'=>'Sudah accepted','B'=>'Belum diterima final dan menunggu ketersediaan/keputusan lanjutan','C'=>'Ditolak permanen','D'=>'Tidak memiliki registration'],'correct'=>'B','explanation'=>'Waiting list memiliki lifecycle berbeda dari accepted.'],
            ['question'=>'Admission offer dapat memerlukan?','options'=>['A'=>'Respons accept/decline dari kandidat','B'=>'Reset password','C'=>'Hard delete registration','D'=>'Penggantian unit otomatis'],'correct'=>'A','explanation'=>'Offer dapat menjadi tahap komitmen setelah keputusan.'],
            ['question'=>'Sebelum publish hasil, quality check sebaiknya mencakup?','options'=>['A'=>'Keputusan, populasi, timing, dan tampilan pendaftar','B'=>'Theme saja','C'=>'Jumlah admin','D'=>'Ukuran database'],'correct'=>'A','explanation'=>'Publication error berdampak langsung ke pendaftar.'],
            ['question'=>'Jika hasil sudah dipublish lalu ditemukan kesalahan, langkah tepat adalah?','options'=>['A'=>'Ubah diam-diam tanpa jejak','B'=>'Gunakan prosedur koreksi, dokumentasikan, dan komunikasikan sesuai kebutuhan','C'=>'Hapus seluruh batch','D'=>'Nonaktifkan semua user'],'correct'=>'B','explanation'=>'Koreksi pasca-publikasi memerlukan governance lebih kuat.'],
            ['question'=>'Daftar ulang sebaiknya selesai ketika?','options'=>['A'=>'Semua requirement yang ditetapkan telah dipenuhi sesuai workflow','B'=>'Admin ingin menutup dashboard','C'=>'Pendaftar login sekali','D'=>'Opening diarsipkan'],'correct'=>'A','explanation'=>'Completion harus menggambarkan kewajiban yang benar-benar selesai.'],
            ['question'=>'Laporan operasional unit sebaiknya?','options'=>['A'=>'Selalu lintas unit','B'=>'Scoped ke unit dan periode/opening yang relevan','C'=>'Hanya berdasarkan screenshot','D'=>'Tidak boleh difilter'],'correct'=>'B','explanation'=>'Scope menjaga relevansi dan authorization.'],
            ['question'=>'Export data unit sebaiknya berisi?','options'=>['A'=>'Sebanyak mungkin kolom','B'=>'Kolom yang diperlukan untuk tujuan kerja','C'=>'Password user','D'=>'Secret aplikasi'],'correct'=>'B','explanation'=>'Data minimization juga berlaku pada export.'],
            ['type'=>'tf','question'=>'File export yang sudah diunduh tetap dilindungi permission aplikasi.','correct'=>false,'explanation'=>'Setelah keluar dari aplikasi, file perlu dikendalikan secara terpisah.'],
            ['question'=>'Audit perubahan konfigurasi membantu menjawab?','options'=>['A'=>'Siapa mengubah apa dan kapan','B'=>'Siapa paling senior','C'=>'Berapa RAM server','D'=>'Apa warna tombol'],'correct'=>'A','explanation'=>'Audit trail merekam actor, waktu, object, dan perubahan.'],
            ['question'=>'NIK, dokumen, data orang tua, pembayaran, dan hasil seleksi sebaiknya?','options'=>['A'=>'Disebar ke semua staff','B'=>'Diakses hanya sesuai kebutuhan pekerjaan','C'=>'Diunggah ke drive pribadi','D'=>'Ditampilkan di halaman public'],'correct'=>'B','explanation'=>'Need-to-know mengurangi paparan data pribadi.'],
            ['type'=>'tf','question'=>'Admin Unit boleh menggunakan data kontak pendaftar untuk tujuan di luar penerimaan selama nomor tersedia di sistem.','correct'=>false,'explanation'=>'Penggunaan data harus mengikuti tujuan yang relevan.'],
            ['question'=>'Akun admin personal penting karena?','options'=>['A'=>'Menjaga akuntabilitas audit dan keamanan credential','B'=>'Membuat menu lebih banyak','C'=>'Menghapus kebutuhan role','D'=>'Mempercepat export'],'correct'=>'A','explanation'=>'Audit actor hanya dapat dipercaya jika akun tidak dibagi.'],
            ['question'=>'Jika data unit lain tiba-tiba terlihat, Admin Unit sebaiknya?','options'=>['A'=>'Gunakan kesempatan untuk membantu','B'=>'Hentikan akses yang tidak perlu dan eskalasi sebagai masalah authorization','C'=>'Export dulu untuk bukti','D'=>'Hapus data unit lain'],'correct'=>'B','explanation'=>'Cross-unit visibility harus dianggap masalah scope/access.'],
            ['question'=>'Saat insiden operasional, tindakan yang sebaiknya dihindari adalah?','options'=>['A'=>'Mencatat waktu dan evidence','B'=>'Membuat banyak perubahan acak sebelum memahami masalah','C'=>'Menghentikan dampak lebih lanjut','D'=>'Eskalasi dengan konteks'],'correct'=>'B','explanation'=>'Perubahan acak menghilangkan evidence dan memperluas dampak.'],
            ['question'=>'Checklist go-live harus diuji dari perspektif?','options'=>['A'=>'Admin saja','B'=>'End-to-end termasuk sisi pendaftar dan mobile','C'=>'Database saja','D'=>'Email provider saja'],'correct'=>'B','explanation'=>'Go-live perlu memvalidasi pengalaman pengguna nyata.'],
            ['type'=>'tf','question'=>'Membuka pendaftaran dulu lalu memperbaiki konfigurasi sambil berjalan adalah praktik yang dianjurkan.','correct'=>false,'explanation'=>'Konfigurasi kritis harus direview sebelum go-live.'],
            ['question'=>'Saat opening aktif dan muncul satu keluhan individual, Admin Unit sebaiknya?','options'=>['A'=>'Langsung ubah workflow global','B'=>'Verifikasi apakah kasus individual atau pola sistemik','C'=>'Pause semua unit','D'=>'Hapus data kasus'],'correct'=>'B','explanation'=>'Jangan mengubah sistem secara reaktif tanpa diagnosis.'],
            ['question'=>'Pola error upload yang berulang dari banyak pendaftar kemungkinan menunjukkan?','options'=>['A'=>'Selalu kesalahan user','B'=>'Masalah sistemik/configuration yang perlu investigasi','C'=>'Tidak ada masalah','D'=>'Role salah'],'correct'=>'B','explanation'=>'Pola berulang adalah sinyal masalah yang lebih luas.'],
            ['question'=>'Saat menutup periode, urutan yang lebih tepat adalah?','options'=>['A'=>'Archive langsung walau banyak proses aktif','B'=>'Close, selesaikan outstanding, review laporan, lalu archive saat tidak operasional','C'=>'Hard delete opening','D'=>'Reset semua registration'],'correct'=>'B','explanation'=>'Penutupan perlu menjaga proses outstanding dan histori.'],
            ['type'=>'tf','question'=>'Archived berarti data historis boleh dihapus otomatis.','correct'=>false,'explanation'=>'Archived memisahkan histori dari operasi aktif, bukan menghapusnya.'],
            ['question'=>'Jika opening hanya perlu dihentikan saat maintenance dua jam, tindakan paling tepat adalah?','options'=>['A'=>'close','B'=>'pause','C'=>'archive','D'=>'delete'],'correct'=>'B','explanation'=>'Pause dirancang untuk penghentian sementara.'],
            ['question'=>'Jika Admin Unit salah memilih close padahal perlu pause, risiko utamanya adalah?','options'=>['A'=>'Makna lifecycle tidak sesuai kebutuhan dan proses resume menjadi tidak tepat','B'=>'Logo hilang','C'=>'Password berubah','D'=>'Semua dokumen public'],'correct'=>'A','explanation'=>'Status harus merepresentasikan kondisi operasional yang benar.'],
            ['question'=>'Mengapa next action penting bagi pendaftar?','options'=>['A'=>'Mengarahkan tindakan yang relevan dengan current stage','B'=>'Menggantikan semua halaman','C'=>'Menentukan role admin','D'=>'Menghapus kebutuhan FAQ'],'correct'=>'A','explanation'=>'Next action mengurangi kebingungan pada proses bertahap.'],
            ['question'=>'Jika custom field sudah tidak relevan tetapi memiliki histori data, tindakan paling aman adalah?','options'=>['A'=>'Hapus kolom secara langsung tanpa analisis','B'=>'Nonaktifkan dari penggunaan baru dan pertahankan/migrasikan histori sesuai kebutuhan','C'=>'Hapus semua registration','D'=>'Ubah nilainya menjadi kosong massal'],'correct'=>'B','explanation'=>'Perubahan schema/form harus mempertahankan integritas data existing.'],
            ['type'=>'tf','question'=>'Payment status boleh diubah hanya untuk membantu pendaftar melewati stage lalu dibetulkan nanti.','correct'=>false,'explanation'=>'Status harus mencerminkan evidence aktual.'],
            ['question'=>'Jika VA program A habis, VA program B sebaiknya?','options'=>['A'=>'Dipinjam tanpa aturan','B'=>'Tidak digunakan jika memang scoped khusus program B; gunakan fallback resmi bila ada','C'=>'Diduplikasi','D'=>'Dihapus'],'correct'=>'B','explanation'=>'Pool program-specific tidak boleh dipinjam sembarangan.'],
            ['question'=>'Jika test session penuh, Admin Unit sebaiknya?','options'=>['A'=>'Mengabaikan kapasitas','B'=>'Buat/ubah kapasitas melalui keputusan operasional yang benar dan komunikasikan dampaknya','C'=>'Edit booking langsung','D'=>'Hapus peserta terakhir'],'correct'=>'B','explanation'=>'Kapasitas harus dikelola sebagai konfigurasi resource.'],
            ['question'=>'Quality check hasil seleksi sebaiknya dilakukan sebelum?','options'=>['A'=>'Data dimasukkan','B'=>'Publication','C'=>'Opening dibuat','D'=>'User login'],'correct'=>'B','explanation'=>'Review sebelum publication mencegah hasil prematur.'],
            ['question'=>'Jika pendaftar sudah accepted tetapi belum memenuhi daftar ulang, status completed sebaiknya?','options'=>['A'=>'Tetap diberikan agar terlihat selesai','B'=>'Tidak diberikan sampai requirement completion terpenuhi','C'=>'Diberikan otomatis saat accepted','D'=>'Tidak pernah digunakan'],'correct'=>'B','explanation'=>'Completed harus menggambarkan proses yang selesai.'],
            ['question'=>'Ketika mengevaluasi laporan, perbandingan antar opening harus mempertimbangkan?','options'=>['A'=>'Periode, definisi status, dan konteks yang sebanding','B'=>'Warna chart','C'=>'Jumlah admin','D'=>'Nama unit saja'],'correct'=>'A','explanation'=>'Perbandingan memerlukan basis yang konsisten.'],
            ['type'=>'tf','question'=>'Mengunduh seluruh data unit ke laptop pribadi untuk berjaga-jaga adalah praktik yang baik.','correct'=>false,'explanation'=>'Salinan lokal tambahan meningkatkan risiko dan biasanya tidak diperlukan.'],
            ['question'=>'Jika staff meminta export di luar kewenangannya, Admin Unit sebaiknya?','options'=>['A'=>'Berikan karena staff internal','B'=>'Verifikasi kebutuhan dan kewenangan; eskalasi bila perlu','C'=>'Kirim sebagian password','D'=>'Ubah role sementara tanpa catatan'],'correct'=>'B','explanation'=>'Data access harus berdasarkan need-to-know dan authorization.'],
            ['question'=>'Tujuan utama audit bukan untuk?','options'=>['A'=>'Merekonstruksi perubahan','B'=>'Mencatat actor dan waktu','C'=>'Menebak motif seseorang tanpa evidence lain','D'=>'Mendukung investigasi'],'correct'=>'C','explanation'=>'Audit memberikan evidence tindakan, bukan kesimpulan psikologis.'],
            ['question'=>'Jika terjadi publikasi hasil terlalu dini, langkah awal adalah?','options'=>['A'=>'Biarkan agar tidak terlihat salah','B'=>'Contain visibilitas bila memungkinkan, catat scope, dan eskalasi koreksi','C'=>'Hapus semua applicant','D'=>'Reset server'],'correct'=>'B','explanation'=>'Containment dan impact assessment perlu dilakukan cepat.'],
            ['question'=>'Admin Unit yang baik ketika menemukan exception berulang sebaiknya?','options'=>['A'=>'Terus menangani manual tanpa catatan','B'=>'Dokumentasikan pola dan eskalasi perbaikan workflow/configuration','C'=>'Beri TU akses lebih tinggi','D'=>'Hapus validation'],'correct'=>'B','explanation'=>'Pola exception dapat menunjukkan kebutuhan perubahan proses.'],
            ['type'=>'tf','question'=>'Mengubah status data menjadi inactive/archived dapat membantu operational view tetap fokus tanpa menghilangkan histori.','correct'=>true,'explanation'=>'Lifecycle status memisahkan data aktif dan historis.'],
            ['question'=>'Sebelum reaktivasi unit atau opening lama, Admin Unit harus?','options'=>['A'=>'Langsung buka agar cepat','B'=>'Review konfigurasi, tanggal, requirement, dan konten sebelum publikasi','C'=>'Hapus histori','D'=>'Reset role TU'],'correct'=>'B','explanation'=>'Konfigurasi lama mungkin tidak relevan lagi.'],
            ['question'=>'Dalam handover antar Admin Unit, yang perlu dipindahkan adalah?','options'=>['A'=>'Password akun','B'=>'Konteks pekerjaan, outstanding issue, dan dokumentasi','C'=>'Session browser','D'=>'Token personal'],'correct'=>'B','explanation'=>'Handover memindahkan konteks, bukan credential.'],
            ['question'=>'Tujuan akhir konfigurasi yang baik adalah?','options'=>['A'=>'Semua menu terisi','B'=>'Proses pendaftar berjalan konsisten, dapat dipahami, dapat diaudit, dan sesuai kebijakan unit','C'=>'Semua field wajib','D'=>'Tidak ada data archived'],'correct'=>'B','explanation'=>'Kualitas konfigurasi diukur dari proses end-to-end, bukan banyaknya setting.'],
        ];

        $this->seedQuestionBank($program, 'scua-v1', $q);
    }
}
