@extends('layouts.app')
@section('title','Pendaftaran - SPMB Taruna Bakti')
@section('content')
<div class="max-w-4xl mx-auto space-y-6">
    <div><h1 class="text-2xl font-bold">Pendaftaran Calon Siswa</h1><p class="text-gray-600">Akun orang tua dapat mengirim lebih dari satu pendaftaran anak.</p></div>
    @if($errors->any())<div class="bg-red-50 border border-red-200 rounded-xl p-4 text-red-700"><ul class="list-disc ml-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form action="{{ route('registration.store') }}" method="POST" class="space-y-6">@csrf
        <div class="bg-white rounded-xl card-shadow p-6 space-y-4"><h2 class="font-bold text-lg">1. Siapa yang mendaftarkan?</h2><div class="grid md:grid-cols-2 gap-4"><div><label class="label-field">Tipe Pendaftaran *</label><select name="registrant_type" class="input-field" required><option value="parent" @selected(old('registrant_type')==='parent')>Orang tua / wali mendaftarkan anak</option><option value="self" @selected(old('registrant_type')==='self')>Calon siswa mendaftar langsung</option></select></div><div><label class="label-field">Hubungan (jika orang tua/wali)</label><select name="registrant_relationship" class="input-field"><option value="">-- Pilih --</option><option value="father">Ayah</option><option value="mother">Ibu</option><option value="guardian">Wali</option><option value="other">Lainnya</option></select></div><div class="md:col-span-2"><label class="label-field">Unit *</label><select name="unit_id" class="input-field" required><option value="">-- Pilih Unit --</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected(old('unit_id')==$unit->id)>{{ $unit->name }}</option>@endforeach</select></div></div></div>
        <div class="bg-white rounded-xl card-shadow p-6"><h2 class="font-bold text-lg mb-4">2. Data Calon Siswa</h2><div class="grid md:grid-cols-2 gap-4"><div><label class="label-field">NIK *</label><input name="nik" value="{{ old('nik') }}" maxlength="16" class="input-field" required></div><div><label class="label-field">Nama Lengkap *</label><input name="full_name" value="{{ old('full_name') }}" class="input-field" required></div><div><label class="label-field">Nama Panggilan</label><input name="nickname" value="{{ old('nickname') }}" class="input-field"></div><div><label class="label-field">Jenis Kelamin *</label><select name="gender" class="input-field" required><option value="L">Laki-laki</option><option value="P">Perempuan</option></select></div><div><label class="label-field">Tempat Lahir *</label><input name="birth_place" value="{{ old('birth_place') }}" class="input-field" required></div><div><label class="label-field">Tanggal Lahir *</label><input type="date" name="birth_date" value="{{ old('birth_date') }}" class="input-field" required></div><div><label class="label-field">Agama</label><input name="religion" value="{{ old('religion','Islam') }}" class="input-field"></div><div><label class="label-field">Telepon</label><input name="phone" value="{{ old('phone') }}" class="input-field"></div><div><label class="label-field">Email Calon Siswa</label><input type="email" name="email" value="{{ old('email') }}" class="input-field"></div><div><label class="label-field">Sekolah Asal</label><input name="previous_school" value="{{ old('previous_school') }}" class="input-field"></div><div><label class="label-field">Tahun Lulus</label><input type="number" name="graduation_year" value="{{ old('graduation_year') }}" class="input-field"></div><div class="md:col-span-2"><label class="label-field">Alamat Rumah *</label><textarea name="home_address" class="input-field" rows="3" required>{{ old('home_address') }}</textarea></div></div></div>
        <div class="bg-white rounded-xl card-shadow p-6"><h2 class="font-bold text-lg mb-4">3. Data Orang Tua</h2><div class="grid md:grid-cols-2 gap-4"><div><label class="label-field">Nama Ayah *</label><input name="father_name" value="{{ old('father_name') }}" class="input-field" required></div><div><label class="label-field">NIK Ayah</label><input name="father_nik" value="{{ old('father_nik') }}" class="input-field"></div><div><label class="label-field">Pekerjaan Ayah</label><input name="father_occupation" value="{{ old('father_occupation') }}" class="input-field"></div><div><label class="label-field">Telepon Ayah</label><input name="father_phone" value="{{ old('father_phone') }}" class="input-field"></div><div><label class="label-field">Penghasilan Ayah</label><input type="number" name="father_income" value="{{ old('father_income') }}" class="input-field"></div><div class="md:col-span-2 border-t pt-4"></div><div><label class="label-field">Nama Ibu *</label><input name="mother_name" value="{{ old('mother_name') }}" class="input-field" required></div><div><label class="label-field">NIK Ibu</label><input name="mother_nik" value="{{ old('mother_nik') }}" class="input-field"></div><div><label class="label-field">Pekerjaan Ibu</label><input name="mother_occupation" value="{{ old('mother_occupation') }}" class="input-field"></div><div><label class="label-field">Telepon Ibu</label><input name="mother_phone" value="{{ old('mother_phone') }}" class="input-field"></div><div><label class="label-field">Penghasilan Ibu</label><input type="number" name="mother_income" value="{{ old('mother_income') }}" class="input-field"></div></div></div>
        <div class="flex justify-end"><button class="btn-primary" type="submit">Kirim Pendaftaran</button></div>
    </form>
</div>
@endsection
