@extends('layouts.app')
@section('title','Progres Pendaftaran')
@section('content')
@php($stages = \App\Models\Registration::STAGES)
<div class="max-w-5xl mx-auto space-y-6">
    @if(session('success'))<div class="bg-green-50 border border-green-200 text-green-800 rounded-xl p-4">{{ session('success') }}</div>@endif
    <div class="bg-white rounded-xl card-shadow p-6"><div class="flex justify-between gap-4"><div><div class="text-blue-600 font-semibold">{{ $registration->registration_number }}</div><h1 class="text-2xl font-bold">{{ $registration->full_name }}</h1><p class="text-gray-600">{{ $registration->unit->name }}</p></div><span class="h-fit rounded-full bg-blue-50 text-blue-700 px-3 py-1 font-semibold">{{ $registration->stageLabel() }}</span></div></div>
    <div class="bg-white rounded-xl card-shadow p-6"><h2 class="font-bold text-lg mb-4">Alur SPMB</h2><div class="grid md:grid-cols-2 gap-3">@foreach($stages as $key=>$label)@php($current = array_search($registration->current_stage,array_keys($stages),true); $index=array_search($key,array_keys($stages),true))<div class="rounded-lg border p-3 {{ $key===$registration->current_stage ? 'border-blue-400 bg-blue-50' : ($index<$current ? 'border-green-200 bg-green-50' : 'border-gray-200') }}"><span class="font-semibold">{{ $loop->iteration }}. {{ $label }}</span></div>@endforeach</div></div>
    @if($registration->data_validation_status==='revision')<div class="bg-amber-50 border border-amber-200 rounded-xl p-5"><h2 class="font-bold">Data perlu perbaikan</h2><p>{{ $registration->data_validation_notes }}</p></div>@endif
    @if($registration->latestPayment)<div class="bg-white rounded-xl card-shadow p-6"><h2 class="font-bold text-lg">Pembayaran Formulir</h2><div class="mt-3 grid md:grid-cols-3 gap-3"><div><span class="text-sm text-gray-500">Virtual Account</span><div class="font-bold">{{ $registration->latestPayment->va_number ?: '-' }}</div></div><div><span class="text-sm text-gray-500">Nominal</span><div class="font-bold">Rp {{ number_format((float)$registration->latestPayment->amount,0,',','.') }}</div></div><div><span class="text-sm text-gray-500">Status</span><div class="font-bold">{{ ucfirst($registration->latestPayment->status) }}</div></div></div>@if($registration->current_stage==='payment')<a href="{{ route('registration.payment',$registration) }}" class="btn-primary inline-block mt-4">Upload Bukti Pembayaran</a>@endif @if($registration->latestPayment->status==='rejected')<p class="mt-3 text-red-700">Ditolak: {{ $registration->latestPayment->rejection_reason }}</p>@endif</div>@endif
    @if($registration->applicant_card_number)<div class="bg-white rounded-xl card-shadow p-6"><h2 class="font-bold text-lg">Kartu Pendaftar</h2><p class="mt-2">Nomor: <strong>{{ $registration->applicant_card_number }}</strong></p><a href="{{ route('registration.card',$registration) }}" target="_blank" class="btn-primary inline-block mt-4">Buka / Cetak Kartu</a></div>@endif
    @if(in_array($registration->current_stage,['documents','document_verification']))<div class="bg-white rounded-xl card-shadow p-6"><h2 class="font-bold text-lg">Berkas</h2><p class="text-gray-600 mt-1">Lengkapi Raport, KK, Akta Kelahiran, dan Foto.</p><a href="{{ route('registration.documents',$registration) }}" class="btn-primary inline-block mt-4">Kelola Berkas</a></div>@endif
    @if($registration->testResults->isNotEmpty())<div class="bg-white rounded-xl card-shadow p-6"><h2 class="font-bold text-lg mb-4">Rangkaian Tes</h2><div class="space-y-3">@foreach($registration->testResults as $result)<div class="border rounded-lg p-3 flex justify-between"><div><strong>{{ $result->admissionTest->name }}</strong><div class="text-sm text-gray-500">{{ $result->admissionTest->scheduled_at?->format('d M Y H:i') ?? 'Jadwal belum ditentukan' }} · {{ $result->admissionTest->location ?: '-' }}</div></div><div class="text-right"><div>{{ ucfirst($result->status) }}</div><div class="font-semibold">{{ $result->score !== null ? 'Nilai '.$result->score : ucfirst($result->result) }}</div></div></div>@endforeach</div></div>@endif
    @if($registration->selection && $registration->selection->decision!=='pending')<div class="bg-white rounded-xl card-shadow p-6"><h2 class="font-bold text-lg">Hasil Seleksi</h2><p class="mt-2 text-xl font-bold">{{ strtoupper(str_replace('_',' ',$registration->selection->decision)) }}</p>@if($registration->current_stage!=='completed')<p class="text-gray-600">Menunggu pengumuman resmi dipublikasikan.</p>@endif</div>@endif
    @if($registration->announcement?->status==='published')<div class="bg-emerald-50 border border-emerald-200 rounded-xl p-6"><h2 class="font-bold text-xl">{{ $registration->announcement->title ?: 'Pengumuman SPMB' }}</h2><p class="mt-2">{{ $registration->announcement->message }}</p></div>@endif
</div>
@endsection
