<?php

namespace App\Filament\Admin\Resources;
use App\Filament\Admin\Resources\AnnouncementResource\Pages;use App\Models\Announcement;use App\Services\RegistrationWorkflowService;use Filament\Forms;use Filament\Forms\Form;use Filament\Resources\Resource;use Filament\Tables;use Filament\Tables\Table;use Illuminate\Database\Eloquent\Builder;
class AnnouncementResource extends Resource
{
    protected static ?string $model=Announcement::class;protected static ?string $navigationIcon='heroicon-o-megaphone';protected static ?string $navigationLabel='Pengumuman';protected static ?string $navigationGroup='Seleksi';protected static ?int $navigationSort=4;
    public static function form(Form $form):Form{return $form->schema([Forms\Components\Select::make('registration_id')->relationship('registration','registration_number')->label('Pendaftaran')->searchable()->preload()->required(),Forms\Components\TextInput::make('title')->label('Judul'),Forms\Components\Textarea::make('message')->label('Pesan')->rows(5),Forms\Components\Select::make('status')->options(['draft'=>'Draft','published'=>'Dipublikasikan'])->required()]);}
    public static function table(Table $table):Table{return $table->columns([Tables\Columns\TextColumn::make('registration.registration_number')->label('No. Registrasi'),Tables\Columns\TextColumn::make('registration.full_name')->label('Calon Siswa')->searchable(),Tables\Columns\TextColumn::make('registration.selection.decision')->label('Hasil')->badge(),Tables\Columns\TextColumn::make('status')->badge(),Tables\Columns\TextColumn::make('published_at')->dateTime('d M Y H:i')->default('-')])->actions([Tables\Actions\Action::make('publish')->label('Publikasikan')->color('success')->requiresConfirmation()->visible(fn(Announcement $record)=>auth()->user()?->can('publish_announcement')&&$record->status!=='published')->action(fn(Announcement $record)=>app(RegistrationWorkflowService::class)->publish($record->registration,auth()->user(),$record->title,$record->message)),Tables\Actions\EditAction::make()]);}
    public static function getPages():array{return ['index'=>Pages\ListAnnouncements::route('/'),'create'=>Pages\CreateAnnouncement::route('/create'),'edit'=>Pages\EditAnnouncement::route('/{record}/edit')];}
    public static function getEloquentQuery():Builder{$q=parent::getEloquentQuery()->with(['registration.unit','registration.selection']);if(auth()->user()?->isTU())$q->whereHas('registration',fn(Builder $x)=>$x->where('unit_id',auth()->user()->unit_id));return $q;}
}
