<?php

namespace App\Filament\Admin\Resources;
use App\Filament\Admin\Resources\SelectionResource\Pages;use App\Models\Registration;use App\Models\Selection;use App\Services\RegistrationWorkflowService;use Filament\Forms;use Filament\Forms\Form;use Filament\Resources\Resource;use Filament\Tables;use Filament\Tables\Table;use Illuminate\Database\Eloquent\Builder;
class SelectionResource extends Resource
{
    protected static ?string $model=Selection::class;protected static ?string $navigationIcon='heroicon-o-trophy';protected static ?string $navigationLabel='Seleksi Akhir';protected static ?string $navigationGroup='Seleksi';protected static ?int $navigationSort=3;
    public static function form(Form $form):Form{return $form->schema([Forms\Components\Select::make('registration_id')->relationship('registration','registration_number')->label('Pendaftaran')->searchable()->preload()->required(),Forms\Components\Select::make('decision')->options(['pending'=>'Belum Diputuskan','accepted'=>'Diterima','rejected'=>'Ditolak','waiting_list'=>'Daftar Tunggu'])->required(),Forms\Components\TextInput::make('final_score')->numeric(),Forms\Components\Textarea::make('notes')]);}
    public static function table(Table $table):Table{return $table->columns([Tables\Columns\TextColumn::make('registration.registration_number')->label('No. Registrasi'),Tables\Columns\TextColumn::make('registration.full_name')->label('Calon Siswa')->searchable(),Tables\Columns\TextColumn::make('registration.unit.name')->label('Unit')->badge(),Tables\Columns\TextColumn::make('final_score')->label('Nilai Akhir'),Tables\Columns\TextColumn::make('decision')->label('Keputusan')->badge()])->actions([Tables\Actions\Action::make('decide')->label('Putuskan')->visible(fn()=>auth()->user()?->can('decide_selection'))->form([Forms\Components\Select::make('decision')->options(['accepted'=>'Diterima','rejected'=>'Ditolak','waiting_list'=>'Daftar Tunggu'])->required(),Forms\Components\TextInput::make('final_score')->numeric(),Forms\Components\Textarea::make('notes')])->action(fn(Selection $record,array $data)=>app(RegistrationWorkflowService::class)->decide($record->registration,auth()->user(),$data['decision'],$data['final_score']??null,$data['notes']??null)),Tables\Actions\EditAction::make()]);}
    public static function getPages():array{return ['index'=>Pages\ListSelections::route('/'),'create'=>Pages\CreateSelection::route('/create'),'edit'=>Pages\EditSelection::route('/{record}/edit')];}
    public static function getEloquentQuery():Builder{$q=parent::getEloquentQuery()->with('registration.unit');if(auth()->user()?->isTU())$q->whereHas('registration',fn(Builder $x)=>$x->where('unit_id',auth()->user()->unit_id));return $q;}
}
